//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvreisAutoservisEntities1 : DbContext
    {
        public EvreisAutoservisEntities1()
            : base("name=EvreisAutoservisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<Servises> Servises { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
