//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvreisMarketplaceEntities : DbContext
    {
        public EvreisMarketplaceEntities()
            : base("name=EvreisMarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Busket_Product> Busket_Product { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<History_Basket> History_Basket { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<PVZ> PVZ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
