//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket_Product
    {
        public int ID { get; set; }
        public int Product_ID { get; set; }
        public int BasketID { get; set; }
        public int UserID { get; set; }

        public Busket_Product(int Product_ID , int BasketID ,int UserID)
        {
            this.Product_ID=Product_ID;
            this.BasketID=BasketID;
            this.UserID=UserID;
        }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
