//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket_Product
    {
        public int ID { get; set; }
        public int Product_ID { get; set; }
        public int UserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public Busket_Product()
        {

        }
        public Busket_Product(int P_ID, int U_ID)
        {
            Product_ID = P_ID;
            UserID = U_ID;
        }
    }
    
}
