//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PriceMoney { get; set; }
        public int SetMoney { get; set; }
        public Nullable<int> ServisID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
         public Details(string name, int priceMoney, int setMoney, int? servisID, int? quantity)
        {
            Name = name;
            PriceMoney = priceMoney;
            SetMoney = setMoney;
            ServisID = servisID;
            Quantity = quantity;
                   }

        public virtual Servises Servises { get; set; }
    }
}
