//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Basket
    {
        public int ID { get; set; }
        public int HistoryID { get; set; }
        public int BasketID { get; set; }
        public History_Basket(int HistoryID, int BasketID)
        {
            this.HistoryID = HistoryID;
            this.BasketID = BasketID;

        }
        public virtual Busket_Product Busket_Product { get; set; }
        public virtual History History { get; set; }
    }
}
