//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Busket_Product = new HashSet<Busket_Product>();
        }
        public User(string password, string login, int P_ID = 1, int money = 10000)
        {
            Password = password;
            Login = login;
            PVZID = P_ID;
            Money = money;

        }
        public int ID { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> PVZID { get; set; }
        public Nullable<int> Money { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Busket_Product> Busket_Product { get; set; }
        public virtual PVZ PVZ { get; set; }
    }
}
